apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - certificate-api.yml
  - ingress-api.yml

images:
  - name: aflobaton/laurel-infra-manager
    newTag: latest